### ISSUE TITLE
How to clear vue instance 

### ISSUE THREAD

**Issue by mingliang7** [Akryum/meteor-vue-blaze#2]
How can i clear vue instance in blaze template ?
this is my code but its not work.
```
Template.onDestroyed(function(){
   Blaze.remove(this.view);
});
```

![vue-instance](https://cloud.githubusercontent.com/assets/5500858/22619096/1d50d93e-eb1f-11e6-8b4b-2a9a86ebda8e.png)

Note: I use FlowRouter and BlazeLayout so when the router change the vue instance is not clear like picture above. thanks in advance!

**Comment by mingliang7** [comment]
I found the solution by remove class of component. $('.component-class').remove()

**Comment by Akryum** [comment]
What you need is `vueComponent.$destroy()` ([doc](https://vuejs.org/v2/api/#vm-destroy)).
